Repository AustrianDataLAB/IndieGameStream, pull requests merged in 2024-06, with the labels that each got.

#45 bugfix/43-frontend-api-communication
  api/cmd/main.go
Labels: bug, priority

#56 Update workflow to push images with semantic version tag
  .github/workflows/build-test-scan-push-images.yml
Labels: devops

#79 Feature/72-delete-game-from-k8s
  api/apis/k8sApi.go
  api/controllers/gameController.go
  api/services/gameService.go
Labels: feature
